// Plain-language help for every diagnostic code: what it means and what to do.
(function (FRE) {
  'use strict';
  FRE.diagHelp = {
    E_UNDEF: ['A name (II_..., IK3_..., MMI_...) is not #defined in any define*.h the server loads. The server logs "Not Found" and uses 0 instead.',
      'Check the spelling, or add the #define first (defineItem.h for II_ items).'],
    E_UNTERM_STR: ['A "quoted text" has no closing quote on its line. The server reads the rest of the line as part of it, which shifts everything after.',
      'Add the missing " .'],
    E_UNTERM_CMT: ['A /* comment is never closed with */. The server ignores everything after it.',
      'Add the missing */ .'],
    E_NUL: ['The file contains a NUL byte. The server stops reading the file there.', 'Remove the NUL byte with a hex editor.'],
    C_BRACES: ['This NPC block never closes with }. The server keeps reading into the next NPC(s) until the end of the file.',
      'Add the missing } at the end of the NPC block.'],
    C_NO_OPEN_BRACE: ['There is no { after the NPC name. The server takes the next word ("setting") as if it were the {, and the inner setting { } braces then make everything balance. It works by accident and is harmless.',
      'Nothing to do. If you ever fix it by hand, add { after the name AND remove one } at the end of the block, otherwise the block structure changes.'],
    C_DUP_NPC: ['Two NPC blocks have the same name (upper/lower case does not matter, across character.inc, character-etc.inc and character-school.inc). The last one loaded replaces the others.',
      'Rename or remove one of them.'],
    C_SLOT: ['A shop tab number outside 0-3. The server does not check it and writes into memory that does not belong to the shop.',
      'Use tab 0, 1, 2 or 3.'],
    C_ITEM: ['The item is not in Spec_Item.txt (or is skipped there), so the shop silently leaves it out.',
      'Pick an existing item, or add the item to Spec_Item.txt first.'],
    C_ARGS: ['The punctuation of this command is wrong (missing comma or parenthesis). The server skips separators without checking, so the following values are read into the wrong arguments.',
      'Fix the ( , ) of the command.'],
    C_HANG: ['A block like SetEquip( or randomItem { is never closed. The server would loop forever at startup.',
      'Close the block.'],
    C_PRICE_CONFLICT: ['AddShopItem\'s price changes the item\'s price for the whole server, not just this shop. With different prices in different shops, the last one loaded wins everywhere.',
      'Use the same price in every shop for this item, or leave the price out to use the item\'s own price.'],
    C_PRICE_MIN1: ['Players pay 1 Penya for this item. Its price (dwCost in Spec_Item.txt, or the last AddShopItem price) is 0, "=" or below 1, and the server charges at least 1 (OnBuyItem, DPSrvr.cpp:3404). A price above 2,147,483,583 also ends up as 1: the server multiplies it by its shop rates as a float, which overflows.',
      'Give the item a price: type one in this shop (AddShopItem) or change its own price (dwCost).'],
    C_PRICE_FROM_OTHER: ['The price here is not this shop\'s own: another NPC\'s AddShopItem line sets the item\'s price (dwCost) for the whole server, and this shop sells it at that price.',
      'Nothing is wrong. To charge a different price, both shops must agree: there is only one price per item.'],
    C_PRICE_ZERO: ['The item is sold for 0 (or less) Penya.', 'Set a positive price unless it is meant to be free.'],
    C_TAB_FULL: ['A shop tab holds at most 100 items. Items beyond that (generated ones first, then AddShopItem ones in file order) are silently left out.',
      'Narrow the AddVendorItem rules of that tab or move items to another tab.'],
    C_RULE_EMPTY: ['This AddVendorItem rule matches no item: no item of that type has a rarity (dwItemRare) inside the range. The server logs a VENDORITEM error and adds nothing.',
      'Check the item type and the rarity range, or remove the rule.'],
    C_CHIP_TYPE: ['AddVenderItem2 only works in chip shops (SetVenderType(1) Red Chip or (2) Donate Chip). In a Penya shop the server ignores it.',
      'Use AddShopItem for Penya shops, or make the NPC a chip shop.'],
    C_RULE_IGNORED: ['Chip shops (SetVenderType(1) or (2)) only sell their AddVenderItem2 items. The server ignores AddVendorItem rules there; they come back if the NPC becomes a Penya shop again.',
      'Nothing to do. Remove the rule if the NPC stays a chip shop for good.'],
    C_FIXED_IN_CHIP: ['AddShopItem items are added to every kind of shop. In a chip shop they are bought with chips, but without the check AddVenderItem2 gets: an item with chip price 0 is free, and one with no chip price breaks the payment. Its Penya price still changes the item\'s price server-wide.',
      'Use AddVenderItem2 in chip shops (switching the shop type in the dropdown does this).'],
    C_CHIP_COST: ['The item has no chip price (dwReferValue1 in Spec_Item.txt), so the chip shop leaves it out.',
      'Type a chip price in the Price column (it is stored in Spec_Item.txt and shared with the other chip shops and the Donation Shop), or remove the item.'],
    C_TAB_FIRST_UNNAMED: ['The shop window puts each named tab at its own position. With no name for the first tab, position 1 is empty, and the client crashes as soon as a player clicks a tab (CWndTabCtrl::SetCurSel hides the "old" tab, which does not exist; WndControl.cpp:5674). Read from the client code, not seen in game.',
      'Give the first tab a name (+ Tab names the lowest free tab), or move the tab names down so they start at the first tab.'],
    C_TAB_UNNAMED_ITEMS: ['Items sold in a tab without a name are never shown: the shop window only builds tabs that have a name (AddVendorSlot; WndShop.cpp:819).',
      'Name the tab with + Tab, or move the items to a named tab.'],
    C_TAB_GAP: ['A tab without a name between named tabs leaves an empty space in the tab bar. Buying still works: each tab keeps its own position (WndControl.cpp:5744).',
      'Optional: name the empty tab with + Tab.'],
    C_NO_TRADE: ['The NPC lists shop items but has no AddMenu(MMI_TRADE). The buy code requires a Trade menu, so players cannot buy here.',
      'If the shop should work, add AddMenu( MMI_TRADE ); to the NPC. If the Trade menu was disabled on purpose, ignore this.'],
    S_ID_ZERO: ['An item id in Spec_Item.txt resolves to 0 (undefined II_). The server stops reading Spec_Item.txt there: every item after it is missing.',
      'Define the II_ in defineItem.h or fix the name.'],
    S_DUP_ID: ['The same item id appears twice in Spec_Item.txt. The later row silently replaces the earlier one.', 'Remove or renumber one row.'],
    S_VER: ['The row\'s version is above 19, so the v19 server skips it.', 'Use a version of 19 or lower.'],
    S_TRUNCATED: ['Spec_Item.txt ends in the middle of a record.', 'Restore the missing values.'],
    T_KEY: ['A line in a .txt.txt string table does not start with an IDS_ key. The server logs an error and skips it.', 'Fix the key.'],
    T_DUP: ['The same IDS_ key appears twice. The first one wins.', 'Remove the duplicate.'],
    DS_BRACES: ['The DONATIONSHOP { block never closes with }. The server\'s reading loop never ends: it hangs at startup.', 'Add the missing } at the end of the block.'],
    DS_FORMAT: ['A DSItem row is not DSItem "Category" II_NAME (the category must be in quotes), or the file has no DONATIONSHOP block. The server reads values in fixed order, so the rest shifts.', 'Fix the row to: DSItem "Category" II_NAME'],
    DS_UNDEF: ['The item name is not #defined (or is 0). The server logs an error and leaves the row out of the shop.', 'Check the II_ name, or add it to defineItem.h first.'],
    DS_NO_ITEM: ['The item is not in Spec_Item.txt, so it cannot be bought (and the client may show a broken entry).', 'Pick an existing item, or add it to Spec_Item.txt first.'],
    DS_NO_PRICE: ['Donation prices are not in DonationShop.inc: each item\'s price is its dwReferValue1 in Spec_Item.txt (donate chips). This item has none, so the server refuses to sell it.', 'Type a chip price in the Price column (it is stored in Spec_Item.txt and shared with the chip shops), or remove the item from the shop.'],
    DS_DUP: ['The same item is listed twice. The shop keeps one entry per item, in the category of the LAST row.', 'Remove one of the rows.'],
    DS_OVERFLOW: ['The client and the server work out the total as an int: price x quantity. A player can buy up to 9,999 at once, so above 214,769 chips the total passes 2,147,483,647 and turns negative. The chip check then passes, and the player gets the items for the chips they have (CDPSrvr::OnBuyDonationItem, DPSrvr.cpp:3636). Read from the C++, not seen in game.',
      'Keep the chip price at 214,769 or less. The same price is used by Red Chip and Donate Chip NPC shops.'],
    DS_CRASH: ['Buying this item in the Donation Shop crashed the server every time in live tests; the cause was never found (commit ae345504). It is left out of the shop on purpose.',
      'Remove the row. Only add it back after the crash is fixed and tested in game.'],
    DS_NO_LEAF: ['The client\'s category tree (Client/Client/DonationShopTree.inc) has no category with this name, so the item is listed only under "All Items" (sorted last), not in any category.',
      'Move the item to one of the existing categories, or add the category with "+ Category" on the left.'],
    DT_ROOT: ['The Donation Shop window opens on the entry "All Items" and looks it up by its exact name. Every group and category must sit inside it.',
      'Put "All Items" back as the one top entry (Undo, or fix Client/Client/DonationShopTree.inc).'],
    DT_DUP: ['The client finds a category by its name, ignoring case. Two entries with the same name show each other\'s items.',
      'Rename one of them.'],
    DT_BRACE: ['The client only looks at the first letter to spot the { and } that open and close a group, so a name starting with one breaks the whole tree.',
      'Start the name with another letter.'],
    DT_CHARS: ['Names are written in quotes in a plain-ASCII file: a quote, a line break, a letter outside plain English, or a space at either end would break the file or stop items from matching.',
      'Use plain letters, digits and signs, without spaces at the ends.'],
    DT_PATCH: ['Without the client change docs/patches/donation-tree.diff, the order of the categories and the line on each item\'s card are fixed in the game\'s code. A category it does not know sorts last and its items say "A cosmetic weapon skin".',
      'Apply docs/patches/donation-tree.diff in FLYFF-V19-SOURCE and build Neuz once; after that every category change works without a rebuild.'],
    DT_ORDER: ['Without the client change docs/patches/donation-tree.diff the game lists items in its own fixed category order, not the order in the sidebar.',
      'Apply docs/patches/donation-tree.diff and build Neuz once.'],
    D_BRACE: ['A define header contains {. The server stops reading defines from that file there.', 'Remove the {.'],
    // Battle Pass (BattlePass.inc, CProject::LoadBattlePass)
    BP_BRACES: ['A BP block is never closed with }. The server keeps looking for it and hangs at startup.', 'Add the missing } .'],
    BP_FORMAT: ['A row or block is not in the shape the server reads, e.g. a texture name without "quotes" (the following values then shift), or a whole block is missing.',
      'Write texture names in quotes, "" for none.'],
    BP_UNDEF: ['The item or monster name is not #defined, so the server reads 0 and the row does nothing useful.', 'Fix the spelling or pick an existing item / monster.'],
    BP_NO_ITEM: ['The item is not in Spec_Item.txt. As a pass it can never be used; as a reward the server logs an error and the player gets nothing.', 'Pick an existing item.'],
    BP_NO_MONSTER: ['The monster id is not in propMover.txt, so no kill ever pays these points.', 'Pick an existing monster.'],
    BP_DUP_ITEM: ['The same item is listed twice. The server keeps the first row (std::map insert) and ignores this one.', 'Remove one of the rows.'],
    BP_DUP_LEVEL: ['Two reward rows have the same level. The ladder is keyed on the level alone, so the first row wins and this one is ignored, even if its season number differs.', 'Remove one of the rows or change its level.'],
    BP_DUP_MONSTER: ['The monster is listed twice. The server keeps the first row and ignores this one.', 'Remove one of the rows.'],
    BP_LEVEL_GAP: ['A level between 1 and the top level has no row. A player who reaches it finds no cost to the next level and never moves on.', 'Add the missing level, or remove the levels above it.'],
    BP_DATE: ['The end date is not a valid YYYYMMDD date. The server turns it into 0, so the season counts as already over.', 'Pick a date with the date box.'],
    BP_DATE_FORMAT: ['The end date has extra digits (hours/minutes) or a day that does not exist. The database keeps only YYYYMMDD, and an impossible day rolls over to the next month.', 'Pick a date with the date box (8 digits).'],
    BP_TYPE: ['No reward level has the pass\'s season number (nType), so players on this season have an empty ladder.', 'Give the rewards the pass\'s nType (Start new season changes both together).'],
    BP_TYPE_ROW: ['This reward level has a different season number (nType) than the pass, so players on this season skip it.', 'Use Start new season, which changes the pass and every reward together.'],
    BP_EXPIRED: ['The season\'s end date has passed. Nobody is put on the pass at login and kills earn no points. The Donation Shop still sells the pass, and the server activates it anyway (CDPSrvr::OnDoBP has no end-date check): the item is used up, the player gets the level 1 reward and nothing more.', 'Use Start new season on the Season page, save, and restart the server soon.'],
    BP_NO_PASS: ['BP1 has no BPItem row, so no season runs at all.', 'Add the pass row by hand (BPItem nType II_... YYYYMMDD).'],
    BP_MULTI_PASS: ['More than one pass row. One season runs at a time; at login the server uses the row with the LOWEST item id, not the first one.', 'Keep one BPItem row.'],
    BP_CLAMP: ['A value is outside what the server accepts (1 to 10,000 points, quantity at least 1). The server silently uses the nearest allowed value.', 'Enter a value in range.'],
    BP_TEXTURE: ['The texture file is not in the client\'s Theme folder, so the reward box shows nothing there.', 'Fix the file name, or copy the texture into Client/Theme.'],
    BP_BAND: ['The monster pays a different amount than the file\'s level band for its level and rank (see the Monster points page). Often its level was changed in propMover.txt after the list was made.',
      'Use "Re-price off-band rows", or keep it if the price is on purpose.'],
    BP_LOGO_UNUSED: ['The banner texture (first quoted name) is read but this client never draws it.', 'Nothing to do; leave it "" .'],
    // Exchanges (Exchange_Script.txt, CExchange::Load_Script)
    EX_FORMAT: ['A block is never closed with }, or a name stands where a number belongs. A missing } makes the server loop forever at startup; a name in a number slot is read as 0.',
      'Add the missing } or write the number.'],
    EX_OUT_OF_STEP: ['The menu uses a block this server does not know (SET_SMELT / SET_ENCHANT_MOVE come from a newer server; this one reads only SET). The server skips the word, ends the menu at the first } inside it, and reads the rest as junk until it is back in step. Every menu that starts inside the junk is never loaded.',
      'Nothing breaks: the NPC\'s window just opens empty and closes. To use those menus, rewrite their blocks as SET, or delete them.'],
    EX_UNDEF: ['A name is not #defined. The exchange loader turns it into -1 without logging anything. As an ingredient nobody can ever have it; as a reward the server crashes when it creates the item; as a text the line or page is blank.',
      'Fix the spelling or pick an existing item / text.'],
    EX_NO_ITEM: ['The item is not in Spec_Item.txt. As a reward the server crashes when it gives it (it reads the item\'s data without checking). As an ingredient the recipe can never be done.',
      'Pick an existing item.'],
    EX_PACKMAX: ['The reward item has dwPackMax 0. The inventory check divides the quantity by it, which crashes the server.', 'Pick another item, or give it a stack size in Spec_Item.txt.'],
    EX_PAY_EMPTY: ['The recipe has no reward line. The server reads past the end of an empty list at startup, and the client divides by zero when it draws the row.',
      'Add at least one reward.'],
    EX_PROB_OVER: ['The reward chances add up to more than 1,000,000 (100%). The server cuts the line that crosses 100% down to fit and drops every line after it.',
      'Lower the chances so they add up to exactly 1,000,000 ("Spread evenly" does this).'],
    EX_PROB_UNDER: ['The reward chances add up to less than 1,000,000 (100%). The server adds the missing part to the last line.',
      'Make them add up to exactly 1,000,000 so the chances are the ones you wrote.'],
    EX_PAYNUM: ['PAY n is how many different rewards one exchange gives. n above the number of lines gives all of them (and logs an error); n = 0 also gives every line.',
      'Set it between 1 and the number of reward lines.'],
    EX_QTY: ['A quantity of 0 or less. As an ingredient the check always passes and nothing is taken, so the reward is free - except -1 (or =), which takes every one of that item the player has.', 'Use a quantity of at least 1.'],
    EX_SET_CAP: ['A menu keeps at most 30 recipes (__NEW_EXCHANGE_V19). The ones after the 30th are dropped without a message.', 'Move the extra recipes to another menu, or remove some.'],
    EX_DUP_MENU: ['The same menu appears twice. The server keeps the FIRST block (std::map insert) and ignores this one.', 'Merge the two blocks or remove one.'],
    EX_ROW_WIDE: ['The exchange window draws each recipe as one row of icons: ingredients, an arrow, then rewards. About 9 icons fit; more are drawn past the window\'s edge.',
      'Use fewer ingredients or rewards, or split the recipe.'],
    EX_NO_NPC: ['No NPC has AddMenu with this menu, so players cannot open it. Many are old events.', 'Nothing to do, unless you want an NPC to offer it (AddMenu in character.inc).'],
    EX_REMOVE_IGNORED: ['This server takes the CONDITION items when the exchange succeeds (__NEW_EXCHANGE_V19) and ignores the REMOVE block. Here the two lists differ, so REMOVE has no effect.',
      'Nothing to do. Ingredient edits here keep REMOVE equal to CONDITION when they already match.'],

    // Add New NPC (validate/newnpc.js, docs/HANDOFF-ADD-NPC.md §6)
    NN_KEY: ['The NPC key must be 1-31 letters, digits or _ and not start with a digit. The map file keeps it in a 32-byte field (Mover.h).', 'Type a key like MaFl_Lumi.'],
    NN_KEY_DUP: ['Another NPC already has this key (upper/lower case does not matter, across the 3 character files). The server would silently replace one with the other.', 'Choose another key.'],
    NN_KEY_NAME: ['The key is also a #define name or a text key. The server reads every word through those tables, so the key would turn into a number or a text.', 'Choose another key.'],
    NN_TEXT: ['A name or tab title is empty, too long (63 characters at most), has a " or a line break, starts/ends with a space, or has a character outside Windows-1252 (shown as ? in game).', 'Use plain letters, digits and common punctuation.'],
    NN_IDS_TAKEN: ['The next free IDS_CHARACTER_INC_ text key is already used in another .txt.txt file. All text files share one table, and the first key wins.', 'Report it: the editor picks the number after the highest one it finds.'],
    NN_MENU: ['The menu is not in defineNeuz.h (the server would turn it into the Dialog menu, id 0) or its number is 350 or more (outside the NPC menu array, no bounds check).', 'Pick a menu from the list.'],
    NN_MENU_NEW: ['No other NPC uses this menu, so nobody has tried it on an NPC in this game.', 'Fine if you know what the menu does; test it in game.'],
    NN_MENU_TWICE: ['The same menu is ticked twice. It shows once.', 'Untick one.'],
    NN_DIALOG: ['The Dialog menu needs a conversation script written in C++ (WorldDialog.dll). The editor cannot make one, so the menu does nothing for a new NPC.', 'Untick Dialog unless a script for this key exists.'],
    NN_MODEL: ['The model is not an MI_ name from defineObj.h, or it has no row in propMover.txt. The server cannot create the NPC.', 'Pick a model from the list (models other NPCs already use).'],
    NN_MODEL_UNPROVEN: ['No NPC that players can see uses this model, so nobody has seen it work in this game (it may be a monster, a door, or a model with missing files).', 'Fine if you test it on the test server first; models used by a visible NPC are proven.'],
    NN_MODEL_FILES: ['The model has an entry in mdlDyna.inc, but its 3D file (Mvr_<name>.o3d) or one of its animations (.ani) is not in Client/Model.', 'Pick another model, or add the missing files to Client/Model first.'],
    NN_NO_MENU: ['The NPC has no right-click menu, so clicking it does nothing.', 'Tick at least one menu (for example Trade).'],
    NN_IMAGE: ['The portrait text key is not known, so the dialog shows no picture.', 'Pick the portrait of an existing NPC, or none.'],
    NN_STRUCTURE: ['The building type (SRT_) is not defined. The server would use 0.', 'Pick one from the list, or none.'],
    NN_TAG_FILES: ['A new building tag is written to defineNeuz.h, etc.inc and etc.txt.txt, and one of them was not found.', 'Pick a folder that has all three, or pick an existing tag.'],
    NN_TAG_FULL: ['The game keeps building tags in a table of MAX_STRUCTURE rows (20). This number is compiled into the game, and every free row is taken.', 'Pick an existing tag. A new row needs MAX_STRUCTURE raised in Source/Resource/defineNeuz.h (and the Server/Resource and Client copies), then a rebuild of WorldServer (Release) and Neuz (NoGameguard): both size a table with it (Project.h:1046). The DatabaseServer does not use it.'],
    NN_TAG_CHARS: ['The tag text is empty, starts or ends with a space, or has a character the game cannot show.', 'Type the tag with plain letters, without the [ ] (the game adds them).'],
    NN_TAG_LONG: ['The game copies the tag into a 32-byte field (szName[32]) without a length check. A tag of 32 characters or more overwrites the memory after it.', 'Shorten the tag to 31 characters at most.'],
    NN_TAG_DUP: ['A tag with this text, or a #define with this SRT_ name, already exists.', 'Pick the existing tag from the list.'],
    NN_TAG_ICON: ['The new tag takes a free row of the building table. The minimap draws icon (row + 6) for it. Rows 14-17 were added in b4b9a465 and work in game; the icon of a newer row has not been checked.', 'After the in-game test, check the NPC\'s minimap icon.'],
    NM_FILES: ['A new exchange menu writes defineNeuz.h, defineText.h, textClient.inc, textClient.txt.txt, Exchange_Script.txt and character.inc. One of them was not found or is read-only.', 'Pick a folder that has all six, in the NPC Shops task.'],
    NM_NPC: ['The NPC was not found, or it is in character-etc.inc / character-school.inc, which this step does not change.', 'Pick an NPC from character.inc.'],
    NM_NONE: ['There is no menu to add.', 'Add at least one menu.'],
    NM_ID_FULL: ['Menu ids go up to MAX_MOVER_MENU - 1 (349). The limit is compiled into the game, and the ids from 282 are used up.', 'Reuse an existing menu, or raise MAX_MOVER_MENU in Source/Resource/defineNeuz.h (and the Server/Resource and Client copies), then rebuild WorldServer (Release) and Neuz (NoGameguard): both size tables with it (Project.h:433, WORLDSERVER/npchecker.h:18). The DatabaseServer does not use it.'],
    NM_NAME: ['A menu name is an MMI_ #define. It must be new, and so must its label TID (TID_ + the name).', 'Choose another name in capital letters, e.g. MMI_WPNPIECE_ENTANESS.'],
    NM_TEXT: ['A label or message is empty, starts or ends with a space, is longer than 255 characters, or has a character the game cannot show.', 'Use plain text.'],
    NM_EMPTY: ['The menu has no exchange, so its window would open with an empty list.', 'Press + Exchange and give it its costs and its reward.'],
    NM_SET_CAP: ['The server keeps at most 30 exchanges per menu (__NEW_EXCHANGE_V19); the rest are dropped without a message.', 'Split the exchanges over two menus.'],
    NM_RECIPE: ['An exchange needs at least one ingredient (else the reward is free) and one reward (an empty PAY crashes the server and the client).', 'Add the missing ingredient or reward.'],
    NM_ITEM: ['An item name is not defined, or a reward is not in Spec_Item.txt. The server reads an unknown name as -1, and paying out an unknown reward crashes it.', 'Pick the item from the list.'],
    NM_COND_TWICE: ['The same item is listed twice in one exchange\'s costs. The game checks each line against everything the player has (CheckCondition, Exchange.cpp:279), so 1 item passes both "×1" lines, and the second removal finds nothing: players pay less than shown.', 'Put the total amount on one line and remove the other.'],
    NM_QTY: ['Quantities must be whole numbers, 1 or more.', 'Fix the quantity.'],
    NM_CHANCE: ['The reward chances of one exchange should add up to 1,000,000. The server cuts the line that goes over, or adds the rest to the last line.', 'Make the chances add up to 1,000,000.'],
    NM_PAYNUM: ['A random exchange gives N of its rewards (PAY N), each picked by chance (GetPayItemList, Exchange.cpp). N must be at least 1 and at most the number of rewards; more than that logs an error and gives fewer.', 'Set "Gives" between 1 and the number of rewards.'],
    NM_RESULT: ['Every exchange shows a success and a failure message (RESULTMSG). They are either two existing texts or two new ones with new TID_ names.', 'Pick two existing texts, or write two new ones.'],
    NN_SHOP_NO_TRADE: ['Shop is off, so the NPC gets no Trade menu and the items in its tabs are not written (the form keeps them).', 'Turn Shop on again to add them, or leave it off.'],
    NN_RULES: ['The rules text needs a name for the right-click menu, a text in plain English letters, digits and punctuation, and a free menu id (282-349).', 'Fill in the Rules text fields.'],
    NN_RULES_PATCH: ['A rules text menu opens its window only with the client change docs/patches/npc-board.diff built into Neuz. Without it the menu opens an empty swap window.', 'Apply the patch in FLYFF-V19-SOURCE and build Neuz.'],
    NN_SHOP_EMPTY: ['Trade is ticked but no tab has an item or a rule. Trade would open an empty shop.', 'Add items, or untick Trade.'],
    NN_TAB: ['Only tabs 0-3 exist (MAX_VENDOR_INVENTORY_TAB). The server does not check the number, so tab 4 or more writes into memory that is not the shop. A tab may be listed only once.', 'Use tabs 0, 1, 2 and 3, each once.'],
    NN_RULE: ['An auto-fill rule needs an IK3_ kind from defineItemkind.h, a job of -1 (any) or a JOB_ number, and a rarity range with 0 <= min <= max.', 'Fix the rule.'],
    NN_RULE_EMPTY: ['No item matches this rule (kind, job, rarity, sold in shops). The server adds nothing and logs VENDORITEM.', 'Widen the rarity range or pick another kind.'],
    NN_ITEM: ['The item is not in defineItem.h, or not in Spec_Item.txt. The shop would leave it out.', 'Pick an item from the item list.'],
    NN_ITEM_TWICE: ['The item is in this tab twice (once by a rule, or twice by hand). Players see it twice.', 'Remove one.'],
    NN_PRICE: ['A price must be a whole number from 1 to 2,147,483,647 (the server reads it with atoi into an int).', 'Fix the price, or leave it empty to use the item\'s own price.'],
    NN_PRICE_GLOBAL: ['AddShopItem\'s price changes the item\'s price in EVERY shop, not only this one.', 'Leave the price empty unless you want that.'],
    NN_PRICE_CONFLICT: ['Another NPC already sets a different price for this item. The last NPC loaded wins everywhere, so the price players see is hard to predict.', 'Use the same price as the other NPC, or leave the price empty.'],
    NN_TAB_FULL: ['A tab shows at most 100 items (MAX_VENDOR_INVENTORY); the rest are silently left out (rule items first, then the hand-picked ones in order).', 'Narrow the rules or move items to another tab.'],
    NN_MAP: ['The server cannot read a new NPC on this map: the map has no .dyo file, or its file does not end with the 0xFFFFFFFF marker the editor inserts before (WdGuildWar1To1 and WdVolcaneYellow start with junk, so the server reads nothing there).', 'Pick another map.'],
    NN_POS: ['x, y, z and the angle must be numbers, and the angle 0 or more and under 360.', 'In game, stand on the spot and type /position, then copy the three numbers.'],
    NN_OVERLAP: ['Another NPC stands less than 4 units away (1 unit in the map file). The two would overlap.', 'Move a few steps away and take /position again.'],
    NN_HEIGHT: ['The height (y) is more than 30 away from the nearest NPC on the map. The NPC may float or be inside the ground.', 'Check y with /position on the exact spot.'],
    // Monster Drops (loaders/drops.js, propMoverEx.inc)
    M_RANGE: ['The block starts with a monster id above the highest id in propMover.txt. The server\'s loader then loops forever (a `continue` inside a do-while), so the WorldServer never finishes starting.', 'Use the MI_ name of a monster that exists in propMover.txt.'],
    M_UNDEF: ['The MI_ name is not defined in any header, so the server reads it as 0 and gives these drops to no real monster.', 'Fix the spelling of the MI_ name.'],
    M_NO_MOVER: ['The id is defined but has no row in propMover.txt, so no such monster ever spawns.', 'Add the drops to a monster that exists.'],
    M_BRACES: ['The monster\'s { } block is broken. Without its closing }, the server reads until the end of the file and loops forever at startup.', 'Close the block with } on its own line.'],
    M_AI: ['The AI { } part of this monster has a word the server does not know. The server stops reading propMoverEx.inc there: this monster and every monster after it lose their drops.', 'Fix the AI line (compare with another monster\'s AI block).'],
    M_DUP: ['The same monster has two blocks. The server adds the drops of both blocks, and the Maxitem of the second one wins.', 'Move the drops into one block.'],
    M_COMMA: ['The line is not written as DropItem(item, chance, upgrade, amount); The server does not check the commas: it reads the values shifted by one, so the chance usually becomes 0 (this is how Sacred Bead of Bubble never dropped, 600269aa).', 'Write the line with three commas.'],
    M_DROP_UNDEF: ['The item name is not defined (it reads as 0) or has no Spec_Item.txt row. The server logs an error at startup and crashes when the item drops.', 'Pick an item that exists.'],
    M_COUNT_ZERO: ['The amount is 0. When the line drops, the server picks a random amount with xRandom(0), which divides by zero and crashes.', 'Use an amount of 1 or more (or -1 for exactly one).'],
    M_GOLD_RANGE: ['DropGold(min, max): the server rolls min + xRandom(max - min). With min = max that is xRandom(0) (a crash); with min above max the number wraps around.', 'Make max bigger than min.'],
    M_KIND_MAX: ['A monster has room for 80 random-gear lines (MAX_DROPKIND). The server does not check: line 81 onward writes past the end of the list in memory.', 'Remove random-gear lines.'],
    M_PROB_OVERFLOW: ['The chance is above 2,147,483,647. The server reads it with atoi, which stops there, so the line drops about 80% of the time instead of always.', 'Nothing to do if 80% is fine. For "always", the server cannot do it in one line: repeat the line (c6b006fe did).'],
    M_PROB_ZERO: ['The chance is 0: the item never drops.', 'Type a chance, or remove the drop.'],
    M_EXTRA_ARGS: ['The DropItem line has more than 4 values (like the event-drop lines of propDropEvent.inc). The server reads the first 4 and skips the rest.', 'Nothing to do; the extra values do nothing.'],
    M_NO_GOLD: ['The monster has no DropGold line, so it gives no Penya. PenyaTable.txt only changes a DropGold roll; it never adds one.', 'Add Penya if players should get some.'],
    M_GOLD_LATE: ['DropGold comes after drop lines that count toward the monster\'s max items per kill. When that many items drop first, the server stops reading the list and the Penya is skipped.', 'Move DropGold up, right after Maxitem.'],
    M_GEN_EDITED: ['This drop was written by one of the gen_*.ps1 scripts. Running that script again rewrites its block and undoes this edit.', 'Change the script too, or don\'t run it again.'],
    // Boxes (loaders/boxes.js: propGiftbox.inc random boxes, propPackItem.inc sets)
    BX_TOO_MANY: ['A random box holds at most 128 lines (MAX_GIFTBOX_ITEM). The server does not check it: line 129 onward writes past the end of the box in memory.', 'Remove lines, or split the items over two boxes.'],
    BX_PACK_TOO_MANY: ['A set holds at most 24 items (MAX_ITEM_PER_PACK). At the 25th the server stops reading propPackItem.inc, so this set and every set after it in the file are lost.', 'Remove items, or split the set over two boxes.'],
    BX_BOTH: ['The box is both a set (propPackItem.inc) and a random box (propGiftbox.inc). When it is used, the server checks sets first, so the random lines are never used.', 'Remove one of the two.'],
    BX_UNDEF: ['The item name is not defined, so the server reads it as item 0. Giving that item crashes the server (GetProp() is NULL).', 'Fix the spelling, or pick an item that exists.'],
    BX_NO_PROP: ['The item has no row in Spec_Item.txt. When the box gives it, the server reads the item\'s settings from nothing and crashes.', 'Pick an item that exists in Spec_Item.txt.'],
    BX_BRACES: ['A box block is never closed with }. The server reads to the end of the file and loops forever at startup.', 'Close the block with } on its own line.'],
    BX_NUM_ZERO: ['The count is 0 or less: the player would get nothing (or a broken stack).', 'Use a count of 1 or more.'],
    BX_NUM_STACK: ['The count is more than one bag slot holds (the item\'s stack size, dwPackMax). The server spreads it over several slots; when the bag has fewer free slots, the box is used up and the item is lost (a random box checks for only 1 free slot; a set checks 1 slot per line).', 'Lower the count to the stack size, and add another line for more.'],
    BX_OVER_100: ['The chances add up to more than 100%. The server rolls 0 - 999,999 and walks down the list, so lines past 100% never drop, and the last line gets what is left (the server sets its running total to exactly 100%).', 'Lower the chances; the editor keeps the total at 100% when you change one.'],
    BX_UNDER_100: ['The chances add up to less than 100%. The server gives the missing part to the last line, so it drops more often than its number says. The table shows the real chances.', 'Nothing to do if that is fine. Changing any chance in the editor makes the numbers add up to 100%.'],
    BX_DUP: ['The same box appears in two blocks. The server adds their lines together into one box (a set takes its time limit from the last block).', 'Move the lines into one block.'],
    BX_NOT_ITEM: ['The box id has no row in Spec_Item.txt, so no player can own this box.', 'Nothing to do unless the box should exist; then add the item first.'],
    BX_SKIPPED: ['The server does not know this word here (only GiftBox and GiftBox2 - GiftBox6 start a box). It skips words one by one until the next box keyword, so whatever box this was is not loaded.', 'Fix the keyword (exact case: GiftBox, GiftBox3 …).'],
    BX_EMPTY: ['A new box needs at least one item: opening an empty box would do nothing.', 'Add an item to the box.'],
    BX_ID_RANGE: ['Every item id below 60,000 is taken. Ids from 60,000 are used by the stackable amplifications (__NEW_STACKABLE_AMPS, ProjectCmn.cpp:593), so the editor does not hand them out.', 'Free an old id by hand first.'],
    BX_TEMPLATE_MISSING: ['A new box copies the Spec_Item.txt row of II_SYS_SYS_SCR_BXMCOOK01 (a usable box with stack 1, like the boxes 949f2cc2 added). That row is missing.', 'Put the row back, or ask for another template.'],
    BX_MODEL_DUP: ['mdlDyna.inc lists the same model (type and index) twice. CModelMng::LoadScript stops the server and the game at startup with a message box (ModelMng.cpp:455).', 'Remove one of the two lines.'],
    BX_EMPTIED: ['The box no longer has any contents. Players who already own it keep the item, but using it does nothing.', 'Undo if that was not meant, or remove the box from shops and drops too.'],
  };
})(globalThis.FRE = globalThis.FRE || {});
