// Plain-language help for every diagnostic code: what it means and what to do.
(function (FRE) {
  'use strict';
  FRE.diagHelp = {
    E_UNDEF: ['A name (II_..., IK3_..., MMI_...) is not #defined in any define*.h the server loads. The server logs "Not Found" and uses 0 instead.',
      'Check the spelling, or add the #define first (defineItem.h for II_ items).'],
    E_UNTERM_STR: ['A "quoted text" has no closing quote on its line. The server reads the rest of the line as part of it, which shifts everything after.',
      'Add the missing " .'],
    E_UNTERM_CMT: ['A /* comment is never closed with */. The server ignores everything after it.',
      'Add the missing */ .'],
    E_NUL: ['The file contains a NUL byte. The server stops reading the file there.', 'Remove the NUL byte with a hex editor.'],
    C_BRACES: ['This NPC block never closes with }. The server keeps reading into the next NPC(s) until the end of the file.',
      'Add the missing } at the end of the NPC block.'],
    C_NO_OPEN_BRACE: ['There is no { after the NPC name. The server takes the next word ("setting") as if it were the {, and the inner setting { } braces then make everything balance. It works by accident and is harmless.',
      'Nothing to do. If you ever fix it by hand, add { after the name AND remove one } at the end of the block, otherwise the block structure changes.'],
    C_DUP_NPC: ['Two NPC blocks have the same name (upper/lower case does not matter, across character.inc, character-etc.inc and character-school.inc). The last one loaded replaces the others.',
      'Rename or remove one of them.'],
    C_SLOT: ['A shop tab number outside 0-3. The server does not check it and writes into memory that does not belong to the shop.',
      'Use tab 0, 1, 2 or 3.'],
    C_ITEM: ['The item is not in Spec_Item.txt (or is skipped there), so the shop silently leaves it out.',
      'Pick an existing item, or add the item to Spec_Item.txt first.'],
    C_ARGS: ['The punctuation of this command is wrong (missing comma or parenthesis). The server skips separators without checking, so the following values are read into the wrong arguments.',
      'Fix the ( , ) of the command.'],
    C_HANG: ['A block like SetEquip( or randomItem { is never closed. The server would loop forever at startup.',
      'Close the block.'],
    C_PRICE_CONFLICT: ['AddShopItem\'s price changes the item\'s price for the whole server, not just this shop. With different prices in different shops, the last one loaded wins everywhere.',
      'Use the same price in every shop for this item, or leave the price out to use the item\'s own price.'],
    C_PRICE_ZERO: ['The item is sold for 0 (or less) Penya.', 'Set a positive price unless it is meant to be free.'],
    C_TAB_FULL: ['A shop tab holds at most 100 items. Items beyond that (generated ones first, then AddShopItem ones in file order) are silently left out.',
      'Narrow the AddVendorItem rules of that tab or move items to another tab.'],
    C_RULE_EMPTY: ['This AddVendorItem rule matches no item: no item of that type has a rarity (dwItemRare) inside the range. The server logs a VENDORITEM error and adds nothing.',
      'Check the item type and the rarity range, or remove the rule.'],
    C_CHIP_TYPE: ['AddVenderItem2 only works in chip shops (SetVenderType(1) Red Chip or (2) Donate Chip). In a Penya shop the server ignores it.',
      'Use AddShopItem for Penya shops, or make the NPC a chip shop.'],
    C_RULE_IGNORED: ['Chip shops (SetVenderType(1) or (2)) only sell their AddVenderItem2 items. The server ignores AddVendorItem rules there; they come back if the NPC becomes a Penya shop again.',
      'Nothing to do. Remove the rule if the NPC stays a chip shop for good.'],
    C_FIXED_IN_CHIP: ['AddShopItem items are added to every kind of shop. In a chip shop they are bought with chips, but without the check AddVenderItem2 gets: an item with chip price 0 is free, and one with no chip price breaks the payment. Its Penya price still changes the item\'s price server-wide.',
      'Use AddVenderItem2 in chip shops (switching the shop type in the dropdown does this).'],
    C_CHIP_COST: ['The item has no chip price (dwReferValue1 in Spec_Item.txt), so the chip shop leaves it out.',
      'Type a chip price in the Price column (it is stored in Spec_Item.txt and shared with the other chip shops and the Donation Shop), or remove the item.'],
    C_NO_TRADE: ['The NPC lists shop items but has no AddMenu(MMI_TRADE). The buy code requires a Trade menu, so players cannot buy here.',
      'If the shop should work, add AddMenu( MMI_TRADE ); to the NPC. If the Trade menu was disabled on purpose, ignore this.'],
    S_ID_ZERO: ['An item id in Spec_Item.txt resolves to 0 (undefined II_). The server stops reading Spec_Item.txt there: every item after it is missing.',
      'Define the II_ in defineItem.h or fix the name.'],
    S_DUP_ID: ['The same item id appears twice in Spec_Item.txt. The later row silently replaces the earlier one.', 'Remove or renumber one row.'],
    S_VER: ['The row\'s version is above 19, so the v19 server skips it.', 'Use a version of 19 or lower.'],
    S_TRUNCATED: ['Spec_Item.txt ends in the middle of a record.', 'Restore the missing values.'],
    T_KEY: ['A line in a .txt.txt string table does not start with an IDS_ key. The server logs an error and skips it.', 'Fix the key.'],
    T_DUP: ['The same IDS_ key appears twice. The first one wins.', 'Remove the duplicate.'],
    DS_BRACES: ['The DONATIONSHOP { block never closes with }. The server\'s reading loop never ends: it hangs at startup.', 'Add the missing } at the end of the block.'],
    DS_FORMAT: ['A DSItem row is not DSItem "Category" II_NAME (the category must be in quotes), or the file has no DONATIONSHOP block. The server reads values in fixed order, so the rest shifts.', 'Fix the row to: DSItem "Category" II_NAME'],
    DS_UNDEF: ['The item name is not #defined (or is 0). The server logs an error and leaves the row out of the shop.', 'Check the II_ name, or add it to defineItem.h first.'],
    DS_NO_ITEM: ['The item is not in Spec_Item.txt, so it cannot be bought (and the client may show a broken entry).', 'Pick an existing item, or add it to Spec_Item.txt first.'],
    DS_NO_PRICE: ['Donation prices are not in DonationShop.inc: each item\'s price is its dwReferValue1 in Spec_Item.txt (donate chips). This item has none, so the server refuses to sell it.', 'Type a chip price in the Price column (it is stored in Spec_Item.txt and shared with the chip shops), or remove the item from the shop.'],
    DS_DUP: ['The same item is listed twice. The shop keeps one entry per item, in the category of the LAST row.', 'Remove one of the rows.'],
    DS_CRASH: ['Buying this item in the Donation Shop crashed the server every time in live tests; the cause was never found (commit ae345504). It is left out of the shop on purpose.',
      'Remove the row. Only add it back after the crash is fixed and tested in game.'],
    DS_NO_LEAF: ['The client\'s category tree (Client/Client/DonationShopTree.inc) has no category with this name, so the item is listed only under "All Items" (sorted last), not in any category.',
      'Move the item to one of the existing categories, or add the category to DonationShopTree.inc in the Client folder by hand.'],
    D_BRACE: ['A define header contains {. The server stops reading defines from that file there.', 'Remove the {.'],
  };
})(globalThis.FRE = globalThis.FRE || {});
